sudo: false
language: python

os:
  - linux

python:
  - "2.7"
  - "3.6"

global:
  env:
    - COMMIT_AUTHOR_EMAIL: "m4.van.dijk@vu.nl"

install:
  # install dependencies
  - (git clone git://github.com/MD-Studio/MDStudio.git --branch master --single-branch && pip install -e MDStudio/mdstudio)

  # install library
  - pip install codecov
  - pip install .

script:
  - coverage run tests

branches:
  only:
    - master

after_success:
  - codecov